# link_language: the tests are C, but they link the C++ Quadrate front-end
test_console = executable('test_console', 'test_console.c',
		include_directories: qdos_inc,
		dependencies: [qdos_core_dep],
		link_language: 'cpp')
test('console', test_console)

test_shell = executable('test_shell', 'test_shell.c',
		include_directories: qdos_inc,
		dependencies: [qdos_core_dep],
		link_language: 'cpp')
test('shell', test_shell)

test_framebuffer = executable('test_framebuffer', 'test_framebuffer.c',
		include_directories: qdos_inc,
		dependencies: [qdos_core_dep],
		link_language: 'cpp')
test('framebuffer', test_framebuffer)

test_keypad = executable('test_keypad', 'test_keypad.c',
		include_directories: qdos_inc,
		dependencies: [qdos_core_dep],
		link_language: 'cpp')
test('keypad', test_keypad)

test_storage = executable('test_storage', 'test_storage.c',
		include_directories: qdos_inc,
		dependencies: [qdos_core_dep],
		link_language: 'cpp')
test('storage', test_storage)

test_complete = executable('test_complete', 'test_complete.c',
		include_directories: qdos_inc,
		dependencies: [qdos_core_dep],
		link_language: 'cpp')
test('complete', test_complete)

test_padui = executable('test_padui', 'test_padui.c',
		include_directories: qdos_inc,
		dependencies: [qdos_core_dep],
		link_language: 'cpp')
test('padui', test_padui)

test_editor = executable('test_editor', 'test_editor.c',
		include_directories: qdos_inc,
		dependencies: [qdos_core_dep],
		link_language: 'cpp')
test('editor', test_editor)

test_mathwords = executable('test_mathwords', 'test_mathwords.c',
		include_directories: qdos_inc,
		dependencies: [qdos_core_dep],
		link_language: 'cpp')
test('mathwords', test_mathwords)
