/**
 * @file wordhelp.c
 * @brief One line on what a word does, for the catalog
 *
 * The interpreter keeps a native's signature but hands out only its name, and
 * a signature says less than a calculator owner needs anyway: `fac` is
 * `(x:f64 -- r:f64)`, which is true of half the list. So the catalog reads
 * this instead, in the notation the HP manuals use -- what is taken, `--`,
 * what is left.
 */

#include "wordhelp.h"

#include <stddef.h>
#include <string.h>

static const struct {
	const char* name;
	const char* help;
} HELP[] = {
		// Quadrate's own operators work as C does: integers wrap and divide whole
		{"!=", "a b -- flag: 1 if a is not b"},
		{"%", "a b -- r: integer remainder, as C has it"},
		{"*", "a b -- a*b: integers wrap; the key is times"},
		{"+", "a b -- a+b: integers wrap; the key is plus"},
		{"++", "n -- n+1"},
		{"-", "a b -- a-b: integers wrap; the key is minus"},
		{"--", "n -- n-1"},
		{"/", "a b -- a/b: whole numbers stay whole; the key is divide"},
		{"<", "a b -- flag: 1 if a < b"},
		{"<=", "a b -- flag: 1 if a <= b"},
		{"==", "a b -- flag: 1 if a equals b"},
		{">", "a b -- flag: 1 if a > b"},
		{">=", "a b -- flag: 1 if a >= b"},
		{"L1", " -- list: statistics list 1"},
		{"L2", " -- list: statistics list 2"},
		{"L3", " -- list: statistics list 3"},
		{"L4", " -- list: statistics list 4"},
		{"L5", " -- list: statistics list 5"},
		{"L6", " -- list: statistics list 6"},
		{"abs", "x -- |x|: absolute value, or a complex's size"},
		{"acos", "x -- acos x: in the angle mode"},
		{"acosh", "x -- acosh x: inverse hyperbolic cosine"},
		{"add", "a b -- a+b: as +"},
		{"alog", "x -- 10^x: shift-log"},
		{"and", "a b -- flag: 1 if both are true"},
		{"angle", "z -- theta: a complex's argument"},
		{"append", "arr x -- arr: x added to the end"},
		{"area", "f g a b -- area between two curves, a to b"},
		{"asin", "x -- asin x: in the angle mode"},
		{"asinh", "x -- asinh x: inverse hyperbolic sine"},
		{"atan", "x -- atan x: in the angle mode"},
		{"atan2", "y x -- angle of the point (x, y)"},
		{"atanh", "x -- atanh x: inverse hyperbolic tangent"},
		{"binomcdf", "n p k -- P(X <= k), binomial"},
		{"binompdf", "n p k -- P(X = k), binomial"},
		{"bits::and", "a b -- a&b: bitwise and"},
		{"bits::not", "a -- ~a: bitwise not"},
		{"bits::or", "a b -- a|b: bitwise or"},
		{"bits::xor", "a b -- a^b: bitwise exclusive or"},
		{"cb", "x -- x^3: cube"},
		{"cbrt", "x -- cube root of x"},
		{"ceil", "x -- the whole number at or above x"},
		{"clear", "... -- : empty the stack (CLST)"},
		{"clr", "n -- : empty register n"},
		{"cls", " -- : clear the output"},
		{"complex", "re im -- z: one complex number (CPLX)"},
		{"conj", "z -- z*: complex conjugate"},
		{"corr", "xs ys -- r: correlation of two lists"},
		{"cos", "x -- cos x: in the angle mode"},
		{"cosh", "x -- cosh x: hyperbolic cosine"},
		{"csplit", "z -- re im: a complex back into two"},
		{"dec", "n -- n-1"},
		{"depth", " -- n: how many values are on the stack"},
		{"div", "a b -- a/b: as /"},
		{"divide", "a b -- a/b: as a calculator divides (the key)"},
		{"drop", "x -- : throw x away"},
		{"dup", "x -- x x: copy x"},
		{"dup2", "a b -- a b a b: copy the top two"},
		{"e", " -- e: 2.718..."},
		{"edit", "\"name\" -- : open a program in the editor"},
		{"eq", "a b -- flag: as =="},
		{"err", " -- msg code: the last error"},
		{"exp", "x -- e^x: shift-ln"},
		{"exp2", "x -- 2^x"},
		{"expreg", "xs ys -- a b: fit y = a*b^x"},
		{"fac", "x -- x!: factorial"},
		{"floor", "x -- the whole number at or below x"},
		{"fmax", "f a b -- x: where f is largest, a to b"},
		{"fmin", "f a b -- x: where f is smallest, a to b"},
		{"fmod", "a b -- r: remainder with a's sign"},
		{"fnint", "f a b -- integral of f from a to b"},
		{"forget", "\"name\" -- : remove a word or program"},
		{"free", "p -- : release what p points to"},
		{"graph", "\"f\" -- : draw word f"},
		{"graph3", "\"f\" -- : draw word f of x and y as a surface"},
		{"gt", "a b -- flag: as >"},
		{"gte", "a b -- flag: as >="},
		{"hypot", "a b -- sqrt(a^2+b^2)"},
		{"i", " -- i: the imaginary unit"},
		{"imag", "z -- im: a complex's imaginary part"},
		{"inc", "n -- n+1"},
		{"intersect", "f g a b -- x: where f and g meet, a to b"},
		{"inv", "x -- 1/x"},
		{"invnorm", "p mu sigma -- x: inverse normal"},
		{"lastx", " -- x: x before the last function (LASTx)"},
		{"len", "arr -- n: how long an array or string is"},
		{"linreg", "xs ys -- a b: fit y = a*x + b"},
		{"ln", "x -- natural log of x"},
		{"lnreg", "xs ys -- a b: fit y = a + b*ln x"},
		{"log", "x -- log10 x: common log"},
		{"log10", "x -- log10 x: common log"},
		{"log2", "x -- log2 x"},
		{"lsto", "xs n -- : keep a list as Ln"},
		{"lt", "a b -- flag: as <"},
		{"lte", "a b -- flag: as <="},
		{"max", "a b -- the larger"},
		{"mean", "xs -- mean of a list"},
		{"median", "xs -- median of a list"},
		{"min", "a b -- the smaller"},
		{"minus", "a b -- a-b: the - key"},
		{"mod", "a b -- r: as %"},
		{"modulo", "a b -- r: remainder with b's sign, as a TI's"},
		{"mul", "a b -- a*b: as *"},
		{"ncr", "n r -- combinations, nCr"},
		{"nderiv", "f x -- d: slope of f at x"},
		{"neg", "x -- -x"},
		{"neq", "a b -- flag: as !="},
		{"nip", "a b -- b: drop the value under x"},
		{"nl", " -- : print a new line"},
		{"normalcdf", "lo hi mu sigma -- P(lo < X < hi), normal"},
		{"normalpdf", "x mu sigma -- density of the normal at x"},
		{"not", "a -- flag: 1 if a is false"},
		{"npr", "n r -- permutations, nPr"},
		{"nth", "arr i -- x: the value at index i"},
		{"or", "a b -- flag: 1 if either is true"},
		{"over", "a b -- a b a: copy the value under x"},
		{"panic", "msg code -- : stop with an error"},
		{"percent", "y x -- y x%: x percent of y (the % key)"},
		{"pi", " -- pi: 3.14159..."},
		{"pick", "a b c -- a b c a: copy the third value up"},
		{"plus", "a b -- a+b: the + key, floats past 64 bits"},
		{"polar", "r theta -- z: complex from size and angle"},
		{"pow", "y x -- y^x"},
		{"print", "x -- : show x on the message row"},
		{"prints", " -- : show the whole stack"},
		{"printv", "x -- : show one value as it is typed"},
		{"pstdev", "xs -- population standard deviation"},
		{"pwrreg", "xs ys -- a b: fit y = a*x^b"},
		{"quadreg", "xs ys -- a b c: fit y = ax^2 + bx + c"},
		{"rand", " -- r: random, 0 to 1"},
		{"randint", "lo hi -- n: random whole number"},
		{"randseed", "n -- : start rand from n"},
		{"rcl", "n -- x: recall register n (RCL)"},
		{"real", "z -- re: a complex's real part"},
		{"rolld", "... -- ...: x to the bottom (R-down)"},
		{"rollu", "... -- ...: the bottom up to x (R-up)"},
		{"root", "f a b -- x: where f is 0, a to b"},
		{"rot", "a b c -- b c a: the third value up"},
		{"round", "x -- x to the nearest whole number"},
		{"set", "arr i x -- arr: put x at index i"},
		{"shl", "a n -- a shifted n bits left"},
		{"shr", "a n -- a shifted n bits right"},
		{"sin", "x -- sin x: in the angle mode"},
		{"sinh", "x -- sinh x: hyperbolic sine"},
		{"sq", "x -- x^2"},
		{"sqrt", "x -- square root of x"},
		{"stdev", "xs -- sample standard deviation"},
		{"sto", "x n -- : keep x in register n (STO)"},
		{"sub", "a b -- a-b: as -"},
		{"sum", "xs -- the sum of a list"},
		{"swap", "a b -- b a: exchange x and y"},
		{"tan", "x -- tan x: in the angle mode"},
		{"tanh", "x -- tanh x: hyperbolic tangent"},
		{"times", "a b -- a*b: the key"},
		{"trunc", "x -- x without its fraction"},
		{"ui::answer", "x -- : leave x on the stack when the app ends"},
		{"ui::arrow", "x0 y0 x1 y1 -- : a line with a head at x1 y1"},
		{"ui::ask", "\"prompt\" -- x ok: ask for a number"},
		{"ui::ask_or", "\"prompt\" x -- x ok: ask, offering x"},
		{"ui::at", "x y -- px py: a point of ui::view as a pixel"},
		{"ui::big", "row \"s\" scale -- : large text"},
		{"ui::box", "x y w h fill -- : draw a rectangle"},
		{"ui::cat", "\"a\" \"b\" -- \"ab\": join two strings"},
		{"ui::circle", "x y r fill -- : draw a circle, fill as ui::box"},
		{"ui::cls", " -- : clear the app's screen"},
		{"ui::frame", "fps -- dt: wait for the next frame; dt in s"},
		{"ui::get", "n -- x: a value kept with ui::put"},
		{"ui::input", "\"prompt\" -- \"s\" ok: ask for text"},
		{"ui::key", " -- key ch got: a key, if one is waiting"},
		{"ui::keyname", "key ch -- \"name\": what a key is called"},
		{"ui::line", "x0 y0 x1 y1 -- : draw a line"},
		{"ui::load", "\"name\" -- x ok: a value ui::save kept"},
		{"ui::menu", "\"title\" items -- i: pick from a list"},
		{"ui::pause", " -- : show what was printed, until a key"},
		{"ui::pixel", "x y on -- : set one pixel"},
		{"ui::plot", "\"f\" -- : graph word f"},
		{"ui::points", "on -- : plot points rather than lines"},
		{"ui::pressed", " -- \"name\": the key pressed, or \"\" if none"},
		{"ui::put", "x n -- : keep x in slot n"},
		{"ui::running", " -- flag: 0 once the app should stop"},
		{"ui::save", "x \"name\" -- : keep x on the card"},
		{"ui::say", "\"s\" -- : show s on the message row"},
		{"ui::show", " -- : put what was drawn on the screen"},
		{"ui::sleep", "ms -- : wait"},
		{"ui::small", "x y \"s\" -- : small text at a pixel"},
		{"ui::spring", "x0 y0 x1 y1 coils width -- : draw a spring"},
		{"ui::str", "x -- \"s\": a number as text"},
		{"ui::text", "col row \"s\" -- : text in a cell"},
		{"ui::ticks", " -- ms: time since power on"},
		{"ui::trace", "x y -- : one more point on a kept curve"},
		{"ui::trace_clear", " -- : start ui::trace afresh"},
		{"ui::view", "x0 x1 y0 y1 -- : the plane ui::at maps, y up"},
		{"ui::wait", " -- key ch: wait for a key"},
		{"ui::window", "x0 x1 y0 y1 -- : the graph's window"},
		{"ui::write", "x y \"s\" scale -- : text at a pixel"},
		{"within", "x lo hi -- flag: 1 if lo <= x <= hi"},
};

const char* qdos_word_help(const char* name) {
	for (size_t i = 0; i < sizeof(HELP) / sizeof(*HELP); i++) {
		if (strcmp(HELP[i].name, name) == 0) {
			return HELP[i].help;
		}
	}
	return NULL;
}
