#!/usr/bin/env python3
"""Rasterise a TTF into src/hal/sim/padfont.c, the simulator's keycap fonts.

Two faces from the one typeface. The larger is what is moulded into a key; the
smaller is the shift legend printed on the case above it, which has to be
noticeably smaller than the cap it belongs to, or the pair reads as two labels
rather than a key and its annotation.

Nothing to do with the panel font. The panel is one bit per pixel and its font
is a bitmap fitted to that grid; the simulator's case is 24-bit RGB, so these
can be antialiased, which is the only way a face this small reads at all. They
never reach the device.

Coverage is baked in as bytes, so the simulator links no rasteriser either.

    tools/genpadfont.py assets/fonts/DejaVuSansCondensed-Bold.ttf 13 10
"""

import sys
from PIL import Image, ImageDraw, ImageFont

FIRST, LAST = 1, 126
OUTPUT = "src/hal/sim/padfont.c"

# Codes 1 to 9, matching the panel font's own symbols in src/ui/font16x24.h, so
# a keycap is the same string either way. The panel has these drawn by hand
# because a typeface cannot survive 16x24 at one bit; here a typeface has them
# already, and better than hand-drawing them again.
SYMBOLS = {
    0x01: ("up", "↑"),
    0x02: ("down", "↓"),
    0x03: ("left", "←"),
    0x04: ("sqrt", "√"),
    0x05: ("divide", "÷"),
    0x06: ("times", "×"),
    0x07: ("plusminus", "±"),
    0x08: ("pi", "π"),
    0x09: ("right", "→"),
    # Above the shared range: these are keycaps and nothing else, so the panel
    # font has no need of them and QDOS_GLYPH_LAST does not have to move. A
    # blank glyph inside the range the shell scans would match every blank cell.
    0x10: ("squared", "²"),
    0x11: ("space", "␣"),
}

PAD = 8  # room around the pen position while measuring


def char_for(code):
    if code in SYMBOLS:
        return SYMBOLS[code][1]
    if 32 <= code <= LAST:
        return chr(code)
    return None


def render(font, text, ascent, descent):
    """Ink bitmap and its offsets from the pen position on the baseline."""
    w = PAD * 2 + int(font.getlength(text)) + PAD
    h = PAD * 2 + ascent + descent
    cell = Image.new("L", (w, h), 0)
    ImageDraw.Draw(cell).text((PAD, PAD + ascent), text, font=font, fill=255, anchor="ls")

    box = cell.getbbox()
    if box is None:
        return None, 0, 0, 0, 0  # space, and anything else with no ink

    x0, y0, x1, y1 = box
    return cell.crop(box), x1 - x0, y1 - y0, x0 - PAD, y0 - (PAD + ascent)


def build(path, size):
    """One face: its coverage blob, its glyph table and its cap height."""
    font = ImageFont.truetype(path, size)
    ascent, descent = font.getmetrics()

    coverage = bytearray()
    glyphs = {}

    for code in range(FIRST, LAST + 1):
        text = char_for(code)
        if text is None:
            glyphs[code] = (0, 0, 0, 0, 0, 0)
            continue

        bitmap, w, h, bx, by = render(font, text, ascent, descent)
        offset = len(coverage)
        if bitmap is not None:
            coverage.extend(bitmap.tobytes())

        advance = int(round(font.getlength(text)))
        glyphs[code] = (w, h, bx, by, advance, offset)

    # Cap height off 'H', which is what a label is centred on
    return coverage, glyphs, -glyphs[ord("H")][3]


def glyph_name(code):
    if code in SYMBOLS:
        return SYMBOLS[code][0]
    if code == ord("*"):
        return "star"
    if code == ord("/"):
        return "slash"
    if code == 0x20:
        return "space"
    return chr(code) if 0x21 <= code <= 0x7E else f"0x{code:02x}"


def emit_face(out, tag, coverage, glyphs):
    out.write(f"static const uint8_t COVERAGE_{tag}[] = {{\n")
    for i in range(0, len(coverage), 20):
        row = ", ".join(f"{b:3d}" for b in coverage[i : i + 20])
        out.write(f"\t\t{row},\n")
    out.write("};\n\n")

    out.write(f"static const qdos_padglyph GLYPHS_{tag}[QDOS_PADFONT_LAST - QDOS_PADFONT_FIRST + 1] = {{\n")
    for code in range(FIRST, LAST + 1):
        w, h, bx, by, advance, offset = glyphs[code]
        out.write(f"\t\t/* {glyph_name(code)} */ {{{w}, {h}, {bx}, {by}, {advance}, {offset}}},\n")
    out.write("};\n\n")


def main():
    path = sys.argv[1]
    cap_size = int(sys.argv[2]) if len(sys.argv) > 2 else 13
    shift_size = int(sys.argv[3]) if len(sys.argv) > 3 else 10

    cap_cov, cap_glyphs, cap_height = build(path, cap_size)
    shift_cov, shift_glyphs, shift_height = build(path, shift_size)

    with open(OUTPUT, "w") as out:
        out.write(f'''/**
 * @file padfont.c
 * @brief Antialiased keycap fonts for the simulator
 *
 * Generated by tools/genpadfont.py from {path.split("/")[-1]}, the cap face at
 * {cap_size}px and the shift face at {shift_size}px. Edit the generator, not this file.
 *
 * Coverage is one byte per pixel, 0 to 255, laid out row-major per glyph. The
 * panel font next door is one bit per pixel because the panel is; these are
 * drawn into the case, which is RGB, so they can afford the greys that make a
 * face this small legible.
 */

#include "padfont.h"

''')
        emit_face(out, "CAP", cap_cov, cap_glyphs)
        emit_face(out, "SHIFT", shift_cov, shift_glyphs)

        out.write(f'''static const int CAP_HEIGHT[QDOS_PADFACE__COUNT] = {{{cap_height}, {shift_height}}};

const qdos_padglyph* qdos_padfont_glyph(qdos_padface face, unsigned char ch) {{
\tif (ch < QDOS_PADFONT_FIRST || ch > QDOS_PADFONT_LAST)
\t\treturn NULL;

\tconst qdos_padglyph* table = (face == QDOS_PADFACE_SHIFT) ? GLYPHS_SHIFT : GLYPHS_CAP;
\treturn &table[ch - QDOS_PADFONT_FIRST];
}}

const uint8_t* qdos_padfont_coverage(qdos_padface face) {{
\treturn (face == QDOS_PADFACE_SHIFT) ? COVERAGE_SHIFT : COVERAGE_CAP;
}}

int qdos_padfont_cap_height(qdos_padface face) {{
\tif (face < 0 || face >= QDOS_PADFACE__COUNT)
\t\treturn 0;
\treturn CAP_HEIGHT[face];
}}

int qdos_padfont_advance(qdos_padface face, const char* text) {{
\tint total = 0;
\tfor (const char* p = text; *p != '\\0'; p++) {{
\t\tconst qdos_padglyph* g = qdos_padfont_glyph(face, (unsigned char)*p);
\t\tif (g != NULL)
\t\t\ttotal += g->advance;
\t}}
\treturn total;
}}
''')

    print(f"{OUTPUT} from {path}")
    print(f"  cap face   {cap_size}px, {len(cap_cov)} bytes, cap height {cap_height}")
    print(f"  shift face {shift_size}px, {len(shift_cov)} bytes, cap height {shift_height}")


if __name__ == "__main__":
    main()
