#!/usr/bin/env python3
"""Pack assets/font8x16.txt into src/ui/font8x16.c.

The editor's font: half the width and two thirds the height of the panel font,
so a program shows 50 columns and 10 lines instead of 24 and 7. The glyphs are
Terminus 8x16, which was drawn for exactly this -- one bit, this cell -- so
unlike the panel font it needed no correcting. See assets/fonts/README.md.

    tools/gensmallfont.py                    # pack
    tools/gensmallfont.py --check            # check only, write nothing
    tools/gensmallfont.py --import FONT.psfu.gz
                                             # rewrite the bitmap from a PSF2
"""

import gzip
import re
import struct
import sys

SOURCE = "assets/font8x16.txt"
OUTPUT = "src/ui/font8x16.c"

CELL_W, CELL_H = 8, 16
FIRST, LAST = 0x20, 0x7E

HEADER = """\
# QDOS 8x16 bitmap font, for the editor -- the source the firmware is built from.
#
# '#' is a lit pixel, '.' is unlit; the leftmost character is the leftmost
# pixel. One block per glyph: a `0xNN name` header, then exactly 16 rows of 8.
# tools/gensmallfont.py packs this into src/ui/font8x16.c.
#
# Imported from Terminus Font 4.20 (Lat2-Terminus16), Copyright (C) 2006
# Dimitar Toshkov Zhekov, GPL-2.0-or-later. Printable ASCII only.
"""


def name_of(code):
    return {0x20: "space"}.get(code, chr(code))


def import_psf(path):
    """ASCII glyphs out of a PSF2 font with a Unicode table."""
    data = gzip.open(path).read() if path.endswith(".gz") else open(path, "rb").read()
    magic, _, header, flags, count, size, height, width = struct.unpack("<8I", data[:32])
    if magic != 0x864AB572 or (width, height) != (CELL_W, CELL_H) or not flags & 1:
        sys.exit(f"{path}: not an 8x16 PSF2 font with a Unicode table")

    table = data[header + count * size :]
    glyph_of = {}
    for index, entry in enumerate(table.split(b"\xff")[:count]):
        # Sequences after 0xFE are combinations, not single characters
        for ch in entry.split(b"\xfe")[0].decode("utf-8", "replace"):
            glyph_of.setdefault(ord(ch), index)

    glyphs = {}
    stride = (width + 7) // 8
    for code in range(FIRST, LAST + 1):
        if code not in glyph_of:
            sys.exit(f"{path}: no glyph for {name_of(code)!r}")
        start = header + glyph_of[code] * size
        rows = []
        for y in range(height):
            byte = data[start + y * stride]
            rows.append("".join("#" if byte & (0x80 >> x) else "." for x in range(width)))
        glyphs[code] = rows
    return glyphs


def write_source(glyphs):
    with open(SOURCE, "w") as out:
        out.write(HEADER)
        for code in range(FIRST, LAST + 1):
            out.write(f"\n0x{code:02x} {name_of(code)}\n")
            out.write("\n".join(glyphs[code]) + "\n")


def load(path):
    glyphs, code, rows = {}, None, []
    for n, line in enumerate(open(path), 1):
        line = line.rstrip("\n")
        if not line or line.startswith("#") and code is None:
            continue
        m = re.match(r"0x([0-9a-fA-F]{2})\b", line)
        if m:
            code, rows = int(m.group(1), 16), []
            glyphs[code] = rows
            continue
        if code is None:
            sys.exit(f"{path}:{n}: pixels before any glyph header")
        rows.append(line)
    return glyphs


def check(glyphs):
    problems = []
    for code in range(FIRST, LAST + 1):
        rows = glyphs.get(code)
        if rows is None:
            problems.append(f"no glyph for {name_of(code)!r}")
            continue
        if len(rows) != CELL_H:
            problems.append(f"{name_of(code)!r} has {len(rows)} rows, not {CELL_H}")
        for row in rows:
            if len(row) != CELL_W or set(row) - {"#", "."}:
                problems.append(f"{name_of(code)!r} has a malformed row {row!r}")
                break
    extra = sorted(set(glyphs) - set(range(FIRST, LAST + 1)))
    if extra:
        problems.append(f"glyphs outside printable ASCII: {extra}")
    return problems


def emit(glyphs, out):
    out.write(f'''/**
 * @file font8x16.c
 * @brief 8x16 bitmap font, for the editor
 *
 * Generated by tools/gensmallfont.py from {SOURCE}. Edit the bitmap, not this file.
 */

/* A row per glyph is what makes this readable at all. */
/* clang-format off */

#include "font8x16.h"

#define FIRST_CHAR 0x{FIRST:02X}
#define LAST_CHAR 0x{LAST:02X}
#define GLYPH_COUNT (LAST_CHAR - FIRST_CHAR + 1)

/* Bit 0 is the leftmost pixel */
static const uint8_t GLYPHS[GLYPH_COUNT][QDOS_SMALL_FONT_H] = {{
''')
    for code in range(FIRST, LAST + 1):
        bits = [sum(1 << x for x, c in enumerate(row) if c == "#") for row in glyphs[code]]
        name = name_of(code).replace("\\", "backslash").replace("*", "star").replace("/", "slash")
        out.write(f"\t/* {name} */ {{{', '.join(f'0x{b:02X}' for b in bits)}}},\n")
    out.write('''};

uint8_t qdos_small_font_row(char ch, int row) {
\tconst unsigned char c = (unsigned char)ch;
\tif (row < 0 || row >= QDOS_SMALL_FONT_H || c < FIRST_CHAR || c > LAST_CHAR)
\t\treturn 0;

\treturn GLYPHS[c - FIRST_CHAR][row];
}
''')


def main():
    args = sys.argv[1:]
    if args[:1] == ["--import"] and len(args) == 2:
        write_source(import_psf(args[1]))
        print(f"{SOURCE} from {args[1]}")

    glyphs = load(SOURCE)
    problems = check(glyphs)
    for p in problems:
        print(f"  {p}", file=sys.stderr)

    if "--check" in args:
        print(f"{SOURCE}: {len(problems)} problems", file=sys.stderr)
        return 1 if problems else 0
    if problems:
        return 1

    with open(OUTPUT, "w") as out:
        emit(glyphs, out)
    print(f"{OUTPUT} from {SOURCE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
